# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f61933fc7eaba07ba0fc1138811b74625c960f788b73f5aa55b6f215f9886e4292e170df5fcf6f610c9b664bbb96acab69e747b90288e8ec489c245db374920

test:
  secret_key_base: c3252eb2ddce52e105dbd5587f20af0222319b244c5ccd2fd8679405fef33b475911488d60d1e863bb46e8fef39737b1730cdb6cb78fc185213880fdde22d515

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
